# Nombre del servicio para identificacion dentro del ecosistema.
spring.application.name=anpa-discovery-server

# Puerto donde se levantara el servidor. 8761 es el puerto predeterminado de Eureka.
server.port=8761

# Configuracion para el cliente de Eureka:
# Indica si este servicio debe registrarse en otro servidor Eureka.
# En este caso, esta configurado como "false" porque este es el servidor principal.
eureka.client.register-with-eureka=false

# Configuracion para el cliente de Eureka:
# Indica si este servicio debe obtener el registro de otras instancias desde otro servidor Eureka.
# Como este es el servidor principal, no necesita buscar registros en otro lugar, por lo que esta configurado como "false".
eureka.client.fetch-registry=false